drop trigger trig_contract;
drop trigger trig_contract_angajat;
drop trigger trig_contract_producator;
drop trigger trig_ldd_contract;
drop trigger trig_tratament_doctor;
drop trigger trig_tratament_zinastere;
drop table CHITANTA;
drop table FACTURA_PRODUCATOR;
drop table FACTURA_PROPRIETAR;
drop table FACTURA;
drop table PRODUSE_DIN_INVENTAR;
drop table INVENTAR;
drop table PRODUS;
drop table CONTRACT_ANGAJAT;
drop table CONTRACT_PRODUCATOR;
drop table CONTRACT;
drop table PRODUCATOR;
drop table FISA_MEDICALA;
drop table ANGAJAT;
drop table DIAGNOSTIC;
drop table ANIMALUT;
drop table PROPRIETAR;
drop table LOCATIE;
drop procedure afis_doctor_favorit;
drop procedure afis_tratamente_animalute;
drop procedure factura_aferenta_fisa;
drop function topclienti;
drop package package_clinica_vet_tav13;
drop package package_clinica_vet_tav14;
drop package package_clinica_vet_utilitare;
drop type tab_imb;
commit;


